"""QuantLib option pricing - system-spec.md S5.2.

Black-Scholes (European, closed-form) is the default engine: exact for a
non-dividend-paying underlying call, ~2 orders of magnitude faster than a
binomial tree (matters for the S6.3 Monte Carlo revaluation grid), and
gives analytic greeks. The known limitation - American puts always carry
early-exercise value BS doesn't capture, worse for dividend payers - is
handled via the binomial engine here plus the comparison harness in
benchmarks/bench_options_pricing.py, which measures whether the gap
actually matters for this system's parameter range rather than assuming
either way.

Measured result (see benchmarks/fixtures/options_pricing_comparison.json,
generated by that harness across 21-90 DTE x 0.20-0.30 put delta x 0-4%
dividend yield): max observed gap was 1.35% of premium, under the spec's
~2% threshold. Black-Scholes is therefore used for puts too, everywhere in
this codebase (strike selection, entry pricing, and the MC grid) - the
binomial engine below exists for this comparison and is not used in the
production instrument-decision path. Re-run the harness and revisit this if
the traded parameter range changes materially (e.g. much longer DTE or
higher-dividend names).

QuantLib usage is confined to this module (plus trading_calendar.py,
risk/covariance.py, risk/montecarlo.py) per the project's own convention -
conversion helpers at the boundary via trading_calendar.to_ql/from_ql.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Optional

import QuantLib as ql

from trading_calendar import to_ql
from brokers.base import Contract

_CALENDAR = ql.UnitedStates(ql.UnitedStates.NYSE)
_DAY_COUNT = ql.Actual365Fixed()

_DEFAULT_RISK_FREE_RATE = 0.04  # used only if the ^IRX fetch in rates.py fails


def _set_eval_date(valuation_date) -> ql.Date:
    vd = to_ql(valuation_date)
    ql.Settings.instance().evaluationDate = vd
    return vd


def _payoff(option_type: str, strike: float) -> ql.PlainVanillaPayoff:
    ql_type = ql.Option.Call if option_type == "call" else ql.Option.Put
    return ql.PlainVanillaPayoff(ql_type, strike)


def _bs_process(spot: float, div_yield: float, rate: float, vol: float, valuation_date) -> ql.BlackScholesMertonProcess:
    vd = to_ql(valuation_date)
    spot_h = ql.QuoteHandle(ql.SimpleQuote(spot))
    div_ts = ql.YieldTermStructureHandle(ql.FlatForward(vd, div_yield, _DAY_COUNT))
    rate_ts = ql.YieldTermStructureHandle(ql.FlatForward(vd, rate, _DAY_COUNT))
    vol_ts = ql.BlackVolTermStructureHandle(ql.BlackConstantVol(vd, _CALENDAR, vol, _DAY_COUNT))
    return ql.BlackScholesMertonProcess(spot_h, div_ts, rate_ts, vol_ts)


def price_black_scholes(
    option_type: str, spot: float, strike: float, expiry: date, valuation_date: date,
    rate: float, div_yield: float, vol: float,
) -> float:
    """European Black-Scholes fair value. Exact for a non-dividend call;
    an approximation (underprices) for puts and dividend payers - S5.2."""
    _set_eval_date(valuation_date)
    option = ql.VanillaOption(_payoff(option_type, strike), ql.EuropeanExercise(to_ql(expiry)))
    process = _bs_process(spot, div_yield, rate, vol, valuation_date)
    option.setPricingEngine(ql.AnalyticEuropeanEngine(process))
    return option.NPV()


def price_binomial(
    option_type: str, spot: float, strike: float, expiry: date, valuation_date: date,
    rate: float, div_yield: float, vol: float, steps: int = 200, american: bool = True,
) -> float:
    """Binomial (CRR) fair value. american=True prices early-exercise value
    BS cannot capture - used by the comparison harness and, if that harness
    finds the gap matters, for put strike selection (S5.2's escalation
    rule)."""
    vd = _set_eval_date(valuation_date)
    exercise = ql.AmericanExercise(vd, to_ql(expiry)) if american else ql.EuropeanExercise(to_ql(expiry))
    option = ql.VanillaOption(_payoff(option_type, strike), exercise)
    process = _bs_process(spot, div_yield, rate, vol, valuation_date)
    option.setPricingEngine(ql.BinomialVanillaEngine(process, "crr", steps))
    return option.NPV()


def implied_vol(
    option_type: str, market_mid: float, spot: float, strike: float, expiry: date,
    valuation_date: date, rate: float, div_yield: float,
    accuracy: float = 1e-4, max_evaluations: int = 100, guess: float = 0.30,
) -> Optional[float]:
    """Solve IV from a market mid price. Returns None on failure (stale or
    crossed quotes commonly raise RuntimeError here) - callers must exclude
    the contract, never substitute a default (S5.2, explicit requirement)."""
    _set_eval_date(valuation_date)
    option = ql.VanillaOption(_payoff(option_type, strike), ql.EuropeanExercise(to_ql(expiry)))
    process = _bs_process(spot, div_yield, rate, guess, valuation_date)
    option.setPricingEngine(ql.AnalyticEuropeanEngine(process))
    try:
        return option.impliedVolatility(market_mid, process, accuracy, max_evaluations)
    except RuntimeError:
        return None


def delta(
    option_type: str, spot: float, strike: float, expiry: date, valuation_date: date,
    rate: float, div_yield: float, vol: float,
) -> float:
    """Analytic Black-Scholes delta (S5.5's strike-selection input)."""
    _set_eval_date(valuation_date)
    option = ql.VanillaOption(_payoff(option_type, strike), ql.EuropeanExercise(to_ql(expiry)))
    process = _bs_process(spot, div_yield, rate, vol, valuation_date)
    option.setPricingEngine(ql.AnalyticEuropeanEngine(process))
    return option.delta()


@dataclass
class AtmIvResult:
    iv: Optional[float]
    note: str


def select_atm_iv(
    contracts: list[Contract], spot: float, valuation_date: date, rate: float, div_yield: float,
) -> AtmIvResult:
    """ATM = strike closest to spot among surviving contracts. If the
    nearest is more than 3% from spot, interpolate IV between the two
    bracketing strikes instead of using a distant one (S5.2's exact rule).
    `contracts` must all share one expiry."""
    if not contracts:
        return AtmIvResult(None, "no contracts to select from")

    nearest = min(contracts, key=lambda c: abs(c.strike - spot))
    rel_dist = abs(nearest.strike - spot) / spot

    if rel_dist <= 0.03:
        iv = implied_vol(nearest.contract_type, nearest.mid, spot, nearest.strike, nearest.expiry, valuation_date, rate, div_yield)
        note = f"ATM strike {nearest.strike} ({rel_dist:.1%} from spot)"
        if iv is None:
            note += " - IV solve failed"
        return AtmIvResult(iv, note)

    below = [c for c in contracts if c.strike <= spot]
    above = [c for c in contracts if c.strike >= spot]
    if not below or not above:
        iv = implied_vol(nearest.contract_type, nearest.mid, spot, nearest.strike, nearest.expiry, valuation_date, rate, div_yield)
        note = f"only one side of spot available among surviving strikes, used nearest ({nearest.strike}, {rel_dist:.1%} from spot)"
        if iv is None:
            note += " - IV solve failed"
        return AtmIvResult(iv, note)

    lo = max(below, key=lambda c: c.strike)
    hi = min(above, key=lambda c: c.strike)
    iv_lo = implied_vol(lo.contract_type, lo.mid, spot, lo.strike, lo.expiry, valuation_date, rate, div_yield)
    iv_hi = implied_vol(hi.contract_type, hi.mid, spot, hi.strike, hi.expiry, valuation_date, rate, div_yield)
    if iv_lo is None or iv_hi is None:
        return AtmIvResult(None, f"IV solve failed on bracketing strikes {lo.strike}/{hi.strike}")
    if hi.strike == lo.strike:
        return AtmIvResult(iv_lo, f"bracket collapsed to single strike {lo.strike}")

    w = (spot - lo.strike) / (hi.strike - lo.strike)
    iv = iv_lo + w * (iv_hi - iv_lo)
    return AtmIvResult(
        iv,
        f"interpolated between {lo.strike} and {hi.strike} (nearest strike {nearest.strike} was {rel_dist:.1%} from spot)",
    )
